apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmsnesia-accounts.fullname" . }}
  labels:
    {{- include "cmsnesia-accounts.labels" . | nindent 4 }}
data:
  spring.application.json: "eyJzcGFyaW5nLmFwcGxpY2F0aW4ubmFtZSI6ImNtc25lc2lhLWFjY291bnRzIiwic3ByaW5nLmRhdGEubW9uZ29kYi51cmkiOiJtb25nb2RiOi8vYXJkaWthcnM6YWJjMTIzQGRzMTE3ODA2Lm1sYWIuY29tOjE3ODA2L2hlcm9rdV8xbmo0a2txYz9yZXRyeVdyaXRlcz1mYWxzZSIsImNtc25lc2lhLnRva2VuLmlzc3VlciI6ImFyZGlrYXJzIiwiY21zbmVzaWEudG9rZW4uYWNjZXNzVG9rZW5FeHBhcmF0aW9uIjoiMjA3MzYwMDAwIiwiY21zbmVzaWEudG9rZW4ucmVmcmVzaFRva2VuRXhwYXJhdGlvbiI6IjQxNDcyMDAwMCIsImNtc25lc2lhLnRva2VuLnNlY3JldCI6IjQ3dUR4RTc0IiwiY21zbmVzaWEudG9rZW4ubWF4IjoiMCJ9Cg=="
